### ISSUE TITLE
Support iPhone 12 Screen Sizes

### ISSUE THREAD

**Issue by jonahollman** [Ekhoo/Device#105]
iPhone 12 Mini: 5.4" with 1080×2340 pixels
iPhone 12 / 12 Pro: 6.1" with 1170×2532 pixels
iPhone 12 Pro Max: 6.7" with 1284×2778 pixels

**Comment by ozgur** [comment]
Fixed in https://github.com/Ekhoo/Device/pull/106

**Comment by mayur43s** [comment]
@Ekhoo, @ozgur Can you please create a new release for newly added iPhone devices?

**Comment by Itlink75** [comment]
Excuse me for this question if it is stupid . I updated the dependency with pod to the latest available and i don t have access to iPhone12 s  ? is there anything i should do to get the access ? Thank you

**Comment by johndpope** [comment]
pod 'Device', :git => 'https://github.com/Ekhoo/Device.git', :commit =>'f2f796b86201cd96271417b99dfd41eb338db395'

**Comment by Itlink75** [comment]
Thank you johnpope . For future unexperiment user like me, in the podfile , replace pod 'Device' by all the text given in the previous line . It is searching the latest updated commit due to the fact that the latest available version doesn t have this update . For iphone 13 , unless a new version is pushed, it is likely that a new commit will be needed .

**Comment by Anderzzon** [comment]
if I use Device.size() on an iPhone 12 mini I get 'screen5_8Inch'
